### ISSUE TITLE
用砚湖易办统一登录系统的学号密码无法登录

### ISSUE THREAD

**Issue by LiuYiLin-CA** [zaxtyson/CDUT_SelectCourse#2]
新生不知道新版教务系统的密码是什么，但是可以用砚湖易办统一登录进入，能否适配使用砚湖易办统一登录？

**Comment by zaxtyson** [comment]
这是我很久之前写的选课程序，今年教务系统换了一套，不知道还能不能用。你可以看看老教务系统能不能登陆，密码一般是你的身份证号。新教务系统可以从砚湖易办进去，但是没法直接登陆，我也不能登录（学校也没管这事🤷‍♂️）
